### ISSUE TITLE
button loader not showing on first click

### ISSUE THREAD

**Issue by debotos** [AlgusDark/bloomer#109]
![error](https://user-images.githubusercontent.com/29367677/44308915-1da2a400-a3e0-11e8-93b4-658dc47b5a6a.png)
At the first click, it's showing just an empty button without button content or text.
on second click it's showing the loader.
```javascript
import React, { Component } from 'react';
import { Button } from 'bloomer';

export default class Subjects extends Component {
  constructor(props) {
    super(props);
    this.state = {
      loading: false
    };
  }
  render() {
    return (
      <div>
        <Button
          isColor="info"
          isOutlined
          isLoading={this.state.loading}
          onClick={() => this.setState({ loading: true })}
        >
          show loading
        </Button>
      </div>
    );
  }
}
```

**Comment by AlgusDark** [comment]
This is not a Bloomer problem. This is a CSS/Bulma issue. Once you click on your `Button`, it's going to keep the `hover` and that's why when you click again, it's going to loose the `hover`

You can fix this by making it as an `Anchor` or other HTML Element:

```javascript
<Button
          isColor="info"
          isOutlined
          isLoading={this.state.loading}
          onClick={this.handleClick}
          render={(props) => <a {...props}>show loading</a>}
          /
        >
```

👍 Thanks to use Bloomer, once I got Internet I'll start making new improvements for the new Version.
