### ISSUE TITLE
no way to use Tab & TabLink with NavLink from 'react-router'

### ISSUE THREAD

**Issue by MunifTanjim** [AlgusDark/bloomer#67]
```jsx
<Tab isActive>
  <TabLink>Name</TabLink>
</Tab>
```
will generate:
```html
<li class="is-active">
  <a>Name</a>
</li>
```

But, `NavLink` from `react-router` can only add className to itself, if it's active.
```jsx
<NavLink to="/path" activeClassName="is-active" >Title</NavLink>
```
if we're in `/path` url, it will generate:
```html
<a href="/path" class="is-active">Title</a>
```

So, even if we compose `NavLink` & `TabLink`, there's still no way to use `bulma`'s style with it. Because, we can't add className to `Tab` when `NavLink` is active.

**Comment by AlgusDark** [comment]
@MunifTanjim , you're right, there is no way to use `NavLink`, but remember that you have `Link` and you can use it like this [example](https://codesandbox.io/s/0qyy25k48v). This example is based on **React Router** [custom link](https://reacttraining.com/react-router/web/example/custom-link) example.

Since Bulma use this kind of classes for tabs, we're unable to change the behavior. I've been really busy but I want to change this kind of stuff (since Bulma is not intended for React while Bloomer is
) and make **Bloomer** React friendly with other famous libraries, `styled-components` is going to help us to achieve this.

Ps: I'm going to close this issue, but you're welcome to open it if this doesn't help you.

**Comment by MunifTanjim** [comment]
Thanks for the response. :smiley: Actually I solved it earlier (and forgot about this issue). I'll leave my solution here:

```jsx
import React from 'react'
import { Route, NavLink } from 'react-router-dom'
import { Tab, TabLink } from 'bloomer'

const NavBarTab = ({ to, exact, ...rest }) => (
  <Route
    path={to}
    exact={exact}
    children={({ match }) => (
      <Tab isActive={match}>
        <TabLink render={() => <NavLink to={to} exact={exact} {...rest} />} />
      </Tab>
    )}
  />
)

export default NavBarTab
```

**Comment by AlgusDark** [comment]
@MunifTanjim lol, actually my first tough was to reply you about the `render` method that most of `anchors` have in **bloomer**. These were tough for this situation when I was facing so many troubles (well, more code) writing the documentation.

Thanks for your solution posted here. I'll leave a code in my comment so we can have both solutions.

**Comment by pauleveritt** [comment]
I know it is poor form to comment on a closed ticket, but this is almost exactly like what I'm seeing. Let me know if you want a new ticket.

- For styling purposes, I'd like to use <NavbarItem href={'/todos'}>Todos</NavbarItem>
- But react-router generates a full page reload for that, because Bloomer generates an <a href="">
- I could instead do <NavbarItem onClick={() => history.push('/todos')}> but that messes up the styling
- <NavBarItem><NavLink to={}> has the correct routing behavior, but wrong styling

If this is confusing, I can do a gist.

**Comment by AlgusDark** [comment]
@pauleveritt a gist would be really helpful :)

**Comment by pauleveritt** [comment]
Here you go: https://gist.github.com/pauleveritt/c5bc6d6f317daede74b97216294bb87f

I suspect the gist will be insufficient as well, as this is an interaction with react-router 4.

**Comment by AlgusDark** [comment]
@pauleveritt yeah, it would be better if you create a small repo... or a http://codesandbox.io example with the minimal stuff you want to do. If that's possible, that would be really helpful.

I believe that you would need the `render` prop on `NavBarItem` but let's see your example.

**Comment by pauleveritt** [comment]
I'll investigate your suggestion first. I'd prefer not to clutter up this ticket with a side issue. Thanks for the fast responses.
