### ISSUE TITLE
CSS not loaded

### ISSUE THREAD

**Issue by kaspermarstal** [AlgusDark/bloomer#69]
The CSS is not loaded when using bloomer with next.js. Take a look at this example:

componentes/hero.js

    import { ... , Hero, ... } from 'bloomer'
    export default () => (
      <Hero isSize='medium'>
      ...
    )

layouts/body.js

    import Head from '../components/head'
    import Header from '../components/header'
    import Footer from '../components/footer'

    export default ({ children }) =>
      <div>
        <Head/>
        <Header/>
        { children }
        <Footer/>
      </div>

pages/index.js

    import Body from '../layouts/body'
    import Hero from '../components/hero'
    export default () =>
      <Body>
        <Hero/>
      </Body>

There are no errors in the dev console. The css from <style jsx global> in the Head component is loading properly, only the Bulma css is missing. I have installed bulma with npm. Loading manually with `<link href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.5.3/css/bulma.min.css" rel="stylesheet" />`. Any idea what I am missing?

This is the components/head.js

    import Head from 'next/head'
    export default () =>
      <Head>
        <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1" />
        <meta charSet="utf-8" />
        <style jsx global>{`
          body { 
            background: #000;
            color: #181b2b;
          }
      `}</style>
     </Head>

**Comment by AlgusDark** [comment]
Are you importing bulma? Right now you need to import bulma in your project
since bloomer *currently* is just a wrapper. So doesn't import bulma by
itself.

In future releases is going to be a styled-componentes library with his own
styles.

El 8 oct. 2017 04:44, "Kasper Marstal" <notifications@github.com> escribió:

The CSS is not loaded when using bloomer with next.js. Take a look at this
example:

componentes/hero.js

import { ... , Hero, ... } from 'bloomer'
export default () => (
  <Hero isSize='medium'>
  ...
)

layouts/body.js

import Head from '../components/head'
import Header from '../components/header'
import Footer from '../components/footer'

export default ({ children }) =>
  <div>
    <Head/>
    <Header/>
    { children }
    <Footer/>
  </div>

pages/index.js

import Body from '../layouts/body'
import Hero from '../components/hero'
export default () =>
  <Body>
    <Hero/>
  </Body>

There are no errors in the dev console. The css from <style jsx global> in
the Head component is loading properly, only the Bulma css is missing. I
have installed bulma with npm. Any idea what I am missing?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/AlgusDark/bloomer/issues/69>, or mute the thread

**Comment by kaspermarstal** [comment]
Appreciate the quick response. How do I load Bulma with import? Could not find it in your otherwise excellent documentation. A naive approach like `import 'bulma'` or `import 'bulma/css/bulma` does not work.

**Comment by AlgusDark** [comment]
Well... That's weird.

If you're using SASS, you can import modules like:

```
@import "bulma/sass/utilities/_all"
@import "bulma/sass/grid/columns"
```

If not, `import 'bulma/css/bulma' should work. Do you have an example nextjs repo where I can test this? I've never tried next but I can try now igual you help me with that :)

**Comment by kaspermarstal** [comment]
Sure! Here it is: https://github.com/kaspermarstal/x-rai-website. Run `npm install` and `npm run dev`. The website is styled because of the [link rel](https://github.com/kaspermarstal/x-rai-website/blob/master/components/head.js#L8). You can remove this line and uncomment [the import](https://github.com/kaspermarstal/x-rai-website/blob/master/pages/index.js#L1) to see the error.

**Comment by AlgusDark** [comment]
Hey, this seems to be a configuration error.

`You may need an appropriate loader to handle this file type`

So, you need something for `Next` like [css-modules](https://github.com/css-modules/css-modules-require-hook).

Please check [this thread](https://github.com/zeit/next.js/issues/544). 

Once that you have the correct loader, you're going to be able to import `bulma` css.

I'm going to close this issue since this is only a configuration problem with Next.js.

Please tell us if you found your solution :)

**Comment by kaspermarstal** [comment]
Thanks will try that and let you know!

**Comment by sandalsoft** [comment]
For those having a similar issue with the CSS not rendering when using create-react-app, this is the import that fixed it for me:

`import 'bulma/css/bulma.css';`

Referenced here: https://github.com/jgthms/bulma/issues/388#issue-190008467

**Comment by srikrsna** [comment]
@kaspermarstal Could you get this to work?
